name: climate_types_zip_zcta
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
  - python=3.10
  - gdal=3
  - rasterio=1.2.10
  - rasterstats=0.19.0
  - geopandas=0.9.0
  - pip=23.1.2
  - pip:
    - hydra-core=1.2.0
    - wget=3
    - snakemake=7.30.1
    - black
