name: climate_types_raster2polygon
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
  - python=3.11
  - gdal=3
  - rasterio=1.2.10
  - rasterstats=0.19.0
  - geopandas=0.9.0
  - pyarrow=14.0.2
  - pip=23.3.2
  - pip:
    - hydra-core==1.2.0
    - snakemake==8.1.2
    - wget==3
