name: climate_types_raster2polygon
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
  - python=3.11
  - gdal=3.6.2
  - rasterio=1.3.6
  - rasterstats=0.19.0
  - geopandas=0.14.2
  - pyarrow=14.0.2
  - pip=23.3.1
  - pip:
    - hydra-core==1.3.2
    - snakemake==8.1.2
    - wget==3.2
    - ipykernel==6.29.4
    - pycountry
    
