defaults:
- datapaths: datapaths
- shapefiles: cb_zctas.yaml

year: 2013

# Climate types raw raster
url:  https://figshare.com/ndownloader/files/12407516
raster: Beck_KG_V1_present_0p5

# used by rasterio
all_touched: true

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}