defaults:
  - _self_
  - datapaths: example
  - shapefiles: example
  - climate_keys.yaml

# Climate types raw raster information
climate_types_url:  https://figshare.com/ndownloader/files/12407516
climate_types_file: Beck_KG_V1_present_0p0083.tif  # it's the one at highest resolution
  # - Beck_KG_V1_present_0p083.tif
  # - Beck_KG_V1_present_0p5.tif
  # - Beck_KG_V1_present_conf_0p0083.tif  # this is uncertainty
  # - Beck_KG_V1_present_conf_0p083.tif
  # - Beck_KG_V1_present_conf_0p5.tif

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}